language: cpp
os: linux
sudo: required
before_install: git clone https://github.com/google/googletest.git && cd googletest/ && mkdir -p build && cd build/ && cmake .. && sudo make install gtest && cd ../..
jobs:
    include:
        - stage: compile
          script: mkdir -p build && cd build/ && cmake .. && cmake --build .
        - stage: test
          script: mkdir -p build && cd build/ && cmake -DCMAKE_BUILD_TYPE="Coverage" .. && make runTests && ./runTests && cd CMakeFiles/runTests.dir/src && gcov *
          after_script: bash <(curl -s https://codecov.io/bash)
matrix:
    allow_failures:
        - stage: test
